
#!/usr/bin/env Rscript
###############################################################
# AgWise Bias Correction & Statistical Downscaling Module
# =======================================================
#
# Concept
# -------
# This script performs bias correction and statistical downscaling
# of subseasonal–seasonal (S2S) or seasonal forecast data within the
# AgWise / AgWISE_Forecast workflow. It uses:
#
#   - Historical hindcast data to learn systematic model biases
#     relative to high-quality reference observations, and
#   - Applies the derived correction to real-time or target-year
#     forecasts to produce bias-adjusted, analysis-ready fields.
#
# The workflow is designed around:
#
#   * Scientific transparency:
#       - Explicit use of hindcasts for calibration only.
#       - Clearly defined reference period and spatial domain.
#   * Consistency across variables and models:
#       - Common folder structure shared with the Python
#         AgWise_Download module.
#       - Unified handling of multiple variables
#         (e.g. PRCP, TMAX, TMIN, TEMP, SRAD).
#   * Operational readiness:
#       - Inputs are taken from standardized "raw" directories
#         (obs + model files generated by Python).
#       - Outputs are written to "processed" directories, separated
#         by country, variable, and forecast year.
#
# Core logic
# ----------
# 1. Read country-specific configuration from 00_config_<COUNTRY>.R,
#    including:
#       - Base directories and country code
#       - Raw and processed folder paths
#       - Calibration years (hindcast period)
#       - Spatial domain (lon/lat limits)
#
# 2. For each variable of interest (e.g. PRCP, TMAX, TMIN, TEMP, SRAD):
#       - Load observation time series for the calibration period.
#       - Load hindcast model data for the same period.
#       - Load corresponding real-time forecasts to be corrected.
#
# 3. Perform bias correction / statistical downscaling:
#       - Estimate biases using hindcasts vs observations.
#       - Apply quantile delta mapping (QDM) or similar method
#         to the forecast data, treating hindcasts only as the
#         calibration set.
#
# 4. Export bias-corrected forecasts:
#       - Save corrected forecast fields as NetCDF in a consistent
#         naming convention under:
#           processed/bias_corrected/forecast/
#       - Optionally generate spatial bias maps for diagnostic
#         purposes (hindcast vs obs, and bias-corrected forecast).
#
# Intended use
# ------------
# This module serves as the R-based post-processing layer for
# AgWise / AgWISE_Forecast and related national agro-climate
# advisory systems. It bridges raw model output and downstream
# applications such as:
#
#   - Agro-climate indices and extremes,
#   - Crop and livestock models (e.g. DSSAT),
#   - Advisory products and decision-support tools,
#   - Skill assessment and verification workflows.
#
# Author
# ------
# Jemal Seid Ahmed, Wuletaw Abera
# Alliance of Bioversity International & CIAT (CGIAR)
# Email: jemal.ahmed@cgiar.org
#
# Date: July 2025
# Version: 1.5

###############################################################
options(warn = -1)
source("00_config_function.R")

###############################################################


run_agwise_seasonal_forecast_BC <- function(
    country_code = "KEN",
    init_month_user = 10,
    season_length_months = 3,
    forecast_year = forecast_year, 
    year_start_obs = year_start_obs,
    year_end_obs = year_end_obs,
    year_hndS = year_hndS,
    year_hndE = year_hndE,
    use_manual_extent = FALSE, extent_manual = c(2, 33, -2, 37),
    manual_domain_name = "User_Domain",
    base_dir = "/Users/alvaro/agwise-planting-date-and-cultivar/Data",
    main_script_dir = "/Users/alvaro/agwise-planting-date-and-cultivar/Scripts/generic/ClimateForecast_BC",
    py_path = "/Users/alvaro/agwise-dssat-workflow/Scripts/generic/ClimateForecast_BC/agwise_env/bin/python",
    py_script = file.path(main_script_dir, "02_run_agwise_multi_country.py"),
    variables_to_bc = c("PRCP", "TMAX", "TMIN", "TEMP", "SRAD"),
    n_cores = max(1, parallel::detectCores() - 1)
) {
  
    setwd(main_script_dir)
      
    #############################################################
    # 1 Build country configration files for both forecast and bias correction
    ###############################################################
    
    build_country_config(country_code = country_code, base_dir = base_dir,
                         use_manual_extent = use_manual_extent, extent_manual = extent_manual,
                         manual_domain_name = "User_Domain",
                         init_month_user = init_month_user, season_length_months = season_length_months,
                         forecast_year = forecast_year, year_start_obs = year_start_obs,
                         year_end_obs = year_end_obs, year_hndS = year_hndS, year_hndE = year_hndE)
    
    
    config_json_path <- file.path(base_dir, country_code,paste0(country_code,"_config_agwise.json"))
    aoi_config <- load_country_config_from_json(config_json_path)
    seasons <- ((aoi_config$init_month - 1 +
             seq_len(aoi_config$season_length_months) - 1) %% 12) + 1

    #############################################################
    # 1.1 Ensure GADM administrative boundaries file exists
    #############################################################
    gadm_dir  <- file.path(aoi_config$dir_raw_admin, "gadm")
    gadm_file <- file.path(gadm_dir, paste0("gadm41_", country_code, "_0_pk.gpkg"))
    
    if (!file.exists(gadm_file)) {
      message("GADM file not found. Generating: ", gadm_file)
      dir.create(gadm_dir, showWarnings = FALSE, recursive = TRUE)
      
      tryCatch({
        aoi_gadm <- geodata::gadm(country = country_code, level = 0, path = gadm_dir)
        terra::writeVector(aoi_gadm, gadm_file, filetype = "GPKG", overwrite = TRUE)
        message("GADM file saved to: ", gadm_file)
      }, error = function(e) {
        message("Warning: Failed to generate GADM file. Error: ", e$message)
        message("The workflow will continue, but country masking may fail.")
      })
    } else {
      message("GADM file found: ", gadm_file)
    }
    
    
    t_all <- Sys.time()
    
    t_down <- Sys.time()
    #############################################################
    # 2 Run Python multi-country downloader & lead time forecast BEFORE bias correction
    ###############################################################
    message("Running AgWise Python downloader for country: ", country_code)
    
    py_cmd <- sprintf(
      "%s %s --data-dir %s --countries %s", shQuote(py_path),
      shQuote(py_script), shQuote(base_dir), country_code)
    
    # Execute command
    status <- system(py_cmd, intern = TRUE)
    
    message("Python downloader output:")
    print(status)
    message("Downloader finished Time: ", round(difftime(Sys.time(), t_down, "mins"), 2), " min")
    
    message("Proceeding to bias correction.........")
    
    #############################################################
    ###3 Bias Correction based on Observation, hindcast and forecast data
    #############################################################
    
    bc_var_cfg <- list(
      PRCP = list(obs_file_pattern="Daily_PRCP_%d_%d.nc", obs_var="PRCP",
                  model_var="PRCP", is_precip=TRUE, method="ptr",
                  scaling.type="multiplicative", units="mm/day"),
      TMAX = list(obs_file_pattern="Daily_TMAX_%d_%d.nc", obs_var="TMAX",
                  model_var="TMAX", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      TMIN = list(obs_file_pattern="Daily_TMIN_%d_%d.nc", obs_var="TMIN",
                  model_var="TMIN", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      TEMP = list(obs_file_pattern="Daily_TEMP_%d_%d.nc", obs_var="TEMP",
                  model_var="TEMP", is_precip=FALSE, method="qdm",
                  scaling.type="additive", units="degC"),
      SRAD = list(obs_file_pattern="Daily_SRAD_%d_%d.nc", obs_var="SRAD",
                  model_var="SRAD", is_precip=FALSE, method="qdm",
                  scaling.type="multiplicative", units="MJ/m2/day"))
    
    ## Variables to process
    variables_to_bc <- intersect(variables_to_bc, names(bc_var_cfg))
    
    if (length(variables_to_bc) == 0) {
      stop("No valid variables selected for bias correction.")
    }
    
    ###############################################################
    # 4. Loop over variables: PRCP, TMAX, TMIN, TEMP, SRAD, ...
    ###############################################################
    for (var_code in variables_to_bc) {
      
      cfg <- bc_var_cfg[[var_code]]
      message("===================================================")
      message("Variable: ", var_code)
      message(" -> obs_file_pattern: ", cfg$obs_file_pattern)
      message(" -> obs_var: ", cfg$obs_var, " | model_var: ", cfg$model_var)
      
      obs_file <- file.path(aoi_config$dir_raw_obs, 
                          sprintf(cfg$obs_file_pattern, aoi_config$year_start_obs, aoi_config$year_end_obs))
    
    
      ###########################################################
      # 4.2 Hindcast & forecast files for this variable
      #     Python naming:
      #       hindcast_<modelid>_<VAR>_...
      #       forecast_<modelid>_<VAR>_...
      ###########################################################
      hind_pattern <- sprintf("^hindcast_.*_%s_.*\\.nc$", var_code)
      fcst_pattern <- sprintf("^forecast_.*_%s_.*\\.nc$", var_code)
      
      hind_files <- list.files(aoi_config$dir_raw_model, pattern = hind_pattern,  full.names = TRUE)
      fcst_files <- list.files(aoi_config$dir_raw_model, pattern = fcst_pattern,full.names = TRUE)
      
      ## Extract model IDs (e.g. "ecmwf51") so we can pair hindcast + forecast
      hind_ids <- sub("^hindcast_([^_]+)_.+\\.nc$", "\\1", basename(hind_files))
      fcst_ids <- sub("^forecast_([^_]+)_.+\\.nc$", "\\1", basename(fcst_files))
      
      model_ids <- intersect(unique(hind_ids), unique(fcst_ids))
      if (length(model_ids) == 0) {
        message("  !! No common model IDs between hindcast and forecast for ", var_code)
        next
      }
      
      
      ###########################################################
      # 4.3 Load observed calibration data (reference)
      ###########################################################
      
      years_calib =  c(aoi_config$year_hndS:aoi_config$year_hndE)
      nc_obs <- loadGridData(dataset = obs_file, season = seasons, var = cfg$obs_var,
        lonLim  = c(aoi_config$extent_obs[2], aoi_config$extent_obs[4]),
        latLim  = c(aoi_config$extent_obs[3], aoi_config$extent_obs[1]),
        years   = years_calib )
      attr(nc_obs$Variable, "units") <- cfg$units
      obs_clim <- climatology(nc_obs)
      
      ###########################################################
      # 4.4 Loop over models that have both hindcast & forecast
      ###########################################################
      for (m in model_ids) {
        message("---------------------------------------------------")
        message("Processing ", var_code, " for model ID: ", m)
        
        ## Select matching hindcast & forecast files
        hind_file <- hind_files[hind_ids == m][1]
        fcst_file <- fcst_files[fcst_ids == m][1]
        
        message("  Hindcast file: ", hind_file)
        message("  Forecast file: ", fcst_file)
        
        
        #--------------------------------------------------------
        # 4.4.1 Load hindcast (calibration) data
        #--------------------------------------------------------
        nc_hind <- tryCatch({
          loadGridData(
            dataset = hind_file,
            var     = cfg$model_var,
            season = seasons,
            lonLim  = c(aoi_config$extent_model[2], aoi_config$extent_model[4]),
            latLim  = c(aoi_config$extent_model[3], aoi_config$extent_model[1]),
            years   = years_calib
          )
        }, error = function(e) {
          message("  Failed to load hindcast: ", hind_file)
          message("  Error: ", e$message)
          return(NULL)
        })
        
        if (is.null(nc_hind)) {
          message("  -> Hindcast load returned NULL, skipping model ", m)
          next
        }
        
        #--------------------------------------------------------
        # 4.4.2 Load forecast data (to be bias-corrected)
        #--------------------------------------------------------
        nc_fcst <- tryCatch({
          loadGridData(
            dataset = fcst_file,
            var     = cfg$model_var,
            season = seasons,
            lonLim  = c(aoi_config$extent_model[2], aoi_config$extent_model[4]),
            latLim  = c(aoi_config$extent_model[3], aoi_config$extent_model[1])
            ## Usually forecast years are a single init year; we can
            ## keep all available times, so we skip 'years=' here.
          )
        }, error = function(e) {
          message("  Failed to load forecast: ", fcst_file)
          message("  Error: ", e$message)
          return(NULL)
        })
        
        
        #--------------------------------------------------------
        # 4.4.3 Bias correction: hindcast calibrates, forecast is newdata
        #     y       = obs (calibration period)
        #     x       = hindcast model (calibration period)
        #     newdata = forecast model (to correct)
        #--------------------------------------------------------
        
        t_bc <- Sys.time()
        
        message("  -> Running biasCorrection (using hindcast as a training data, forecast)...")
        bc_method <- if (cfg$is_precip) "ptr" else "qdm"
        nc_fcst_bc <- biasCorrection(y = nc_obs, x = nc_hind, newdata = nc_fcst,
          precipitation = cfg$is_precip, window = c(30, 7), method = bc_method,
          #cross.val     = "kfold",
          #folds = list(1990:1996, 1997:2002, 2011:2016),
          #consecutive   = cfg$is_precip,
          scaling.type  = cfg$scaling.type, parallel = TRUE,
          max.ncores = n_cores)
        
        mask <- gridArithmetics(nc_obs, 0, operator = "*")
        ## Bias-corrected forecast regridded to obs grid
        nc_fcst_bc_interp <- interpGrid(nc_fcst_bc, getGrid(nc_obs), ncores = n_cores)
        
        message("BC time: ", round(difftime(Sys.time(), t_bc, "mins"), 2), " min")
        
        #--------------------------------------------------------
        # 4.4.4 Export bias-corrected FORECAST only
        #--------------------------------------------------------
        ## Use model ID 'm' and forecast years for naming
        fcst_years_str <- paste(aoi_config$forecast_year, collapse = "-")
        
        outFile <- file.path(aoi_config$dir_bc_fcst, sprintf("%s_daily_%s_forecast_BC_%s.nc",var_code, m, fcst_years_str))
        
        message("  -> Writing bias-corrected FORECAST NetCDF: ", outFile)
        t_nc <- Sys.time()
        
        nc_fcst_bc_interp$Variable$varName = cfg$model_var
        attr(nc_fcst_bc_interp$Variable, "longname") <- "Bias-corrected seasonal forecast"
        
        
        nc_bc_rast <- terra::rast(grid2sp(nc_fcst_bc_interp))
        time(nc_bc_rast) <- as.Date(nc_fcst_bc_interp$Dates$start)
        # 
        
        aoi <- terra::vect(file.path(aoi_config$dir_raw_admin, "gadm", 
                                     paste0("gadm41_",country_code, "_0_pk.rds")))  
        nc_bc_rast_masked <- terra::mask(nc_bc_rast, aoi)
        
        tryCatch({

          terra::writeCDF(
              x = nc_bc_rast_masked,
              filename = outFile,
              varname = as.character(nc_fcst_bc_interp$Variable$varName),
              unit = as.character(attr(nc_fcst_bc_interp$Variable, "units")),
              atts = globalAttributeList,
              prec = "double",
              missval = -999,
              compression = 9,
              overwrite = TRUE
          )

          message("SUCCESSFULLY WROTE:")
          message(outFile)
          message("Exists? ", file.exists(outFile))

      }, error = function(e) {

          message("writeCDF FAILED")
          message(e$message)

      })
        
        # loadeR.2nc::grid2nc( data = nc_fcst_bc, , 
        #                      NetCDFOutFile = outFile, prec = "double", missval = -999, shuffle = TRUE, compression = 0,
        #    globalAttributes = globalAttributeList, verbose = T)
        
        # 4.4.6 Clean up RAM
        #--------------------------------------------------------
        
        message("  -> Finished ", var_code, " for model ID: ", m)
      }
    }
    
    message("Forecast is ready for all variables: Total runtime: ", round(difftime(Sys.time(), t_all, "mins"), 2), " min")
}
